import keyMirror from 'key-mirror';

export default keyMirror({
    GET_PROBLEMS: null,
    SAVE_PROBLEMS: null,
    DELETE_PROBLEMS: null,

    GET_PROBLEMS_SUCCESS: null,
    GET_PROBLEMS_FAILURE: null,

    GET_PROBLEM_SUCCESS: null,
    GET_PROBLEM_FAILURE: null,

    GET_TAGS_SUCCESS: null,
    GET_TAGS_FAILURE: null,

    GET_TAG_SUCCESS: null,
    GET_TAG_FAILURE: null,

    GET_TAGS_All_SUCCESS: null,
    GET_TAGS_All_FAILURE: null,

    UPDATE_PROBLEM_FAILURE: null,
    UPDATE_PROBLEM_SUCCESS: null,

    DELETE_PROBLEMS_SUCCESS: null,
    DELETE_PROBLEMS_FAILURE: null,

    ADD_PROBLEM_SUCCESS: null,
    ADD_PROBLEM_FAILURE: null,

    GET_STATUS_SUCCESS: null,
    GET_STATUS_FAILURE: null,

    GET_CODESOURCE_SUCCESS: null,
    GET_CODESOURCE_FAILURE: null,

    GET_USERS_SUCCESS: null,
    GET_USERS_FAILURE: null,

    USER_REGISTER_SUCCESS: null,
    USER_REGISTER_FAILURE: null,

    USER_LOGIN_SUCCESS: null,
    USER_LOGIN_FAILURE: null,

    GET_USERS_BYTIME_SUCCESS: null,
    GET_USERS_BYTIME_FAILURE: null,

    GET_CONTEST_SUCCESS: null,
    GET_CONTEST_FAILURE: null,

    GET_CONTESTS_SUCCESS: null,
    GET_CONTESTS_FAILURE: null,

    ADD_CONTEST_FAILURE: null,
    ADD_CONTEST_SUCCESS:null,

    GET_CONTESTS_PROBLEM_SUCCESS: null,
    GET_CONTESTS_PROBLEM_FAILURE: null,

    GET_CONTEST_PROBLEMS_SUCCESS: null,
    GET_CONTEST_PROBLEMS_FAILURE: null,

    GET_CONTESTS_PROBLEMS_SUCCESS: null,
    GET_CONTESTS_PROBLEMS_FAILURE: null,

    GET_CONTESTS_STATISTICS_SUCCESS: null,
    GET_CONTESTS_STATISTICS_FAILURE: null,

    GET_CONTESTS_RANKLIST_SUCCESS: null,
    GET_CONTESTS_RANKLIST_FAILURE: null,

    GET_OWN_CONTESTS_SUCCESS: null,
    GET_OWN_CONTESTS_FAILURE: null,

    CODE_SUCCESS: null, //还没用
    CODE_ERROR: null, //还没用

    SUBMIT_CODE_SUCCESS: null,
    SUBMIT_CODE_ERROR: null,

    TAGS_TO_ROBLEMS: null,

    GET_ROAD_SUCCESS: null,
    GET_ROAD_FAILURE: null,

    UPDATE_USER_FAILURE: null,
    UPDATE_USER_SUCCESS: null,

    GET_OWN_STATUS_SUCCESS: null,
    GET_OWN_STATUS_FAILURE: null,

    GET_OWN_CHALLENGING_SUCCESS: null,
    GET_OWN_CHALLENGING_FAILURE: null,

    GET_USER_SUCCESS: null,
    GET_USER_FAILURE: null,

    GET_ROLES_SUCCESS: null,
    GET_ROLES_FAILURE: null,


    UPDATE_PASSWORD_FAILURE: null,
    UPDATE_PASSWORD_SUCCESS: null,

    GETBACK_PASSWORD_FAILURE: null,
    GETBACK_PASSWORD_SUCCESS: null,

    GET_NEWS_ALL_SUCCESS: null,
    GET_NEWS_ALL_FAILURE: null,

    GET_NEWS_SUCCESS: null,
    GET_NEWS_FAILURE: null,

    GET_ABOUT_SUCCESS: null,
    GET_ABOUT_FAILURE: null,

    GET_ABOUTS_SUCCESS: null,
    GET_ABOUTS_FAILURE: null,

    GET_DAY_SUBMIT_SUCCESS: null,
    GET_DAY_SUBMIT_FAILURE: null,


    GET_OWN_COLLECTION_SUCCESS: null,
    GET_OWN_COLLECTION_FAILURE: null,

    GET_ALL_SUBMIT_SUCCESS: null,
    GET_ALL_SUBMIT_FAILURE: null,

    GET_ALL_PROBLEM_SUCCESS: null,
    GET_ALL_PROBLEM_FAILURE: null,

    GET_PROBLEM_ADD_NOTE_SUCCESS: null,
    GET_PROBLEM_ADD_NOTE_FAILURE: null,

    GET_PROBLEM_NOTE_SUCCESS: null,
    GET_PROBLEM_NOTE_FAILURE: null,

    COLLECT_PROBLEM_SUCCESS: null,
    COLLECT_PROBLEM_FAILURE: null,

    ADD_TAGS_SUCCESS: null,
    ADD_TAGS_FAILURE: null,

    GET_OWN_TAGS_SUCCESS: null,
    GET_OWN_TAGS_FAILURE: null,

    DELETE_TAG_SUCCESS: null,
    DELETE_TAG_FAILURE: null,


    GET_CHALLENGE_PROBLEM_SUCCESS: null,
    GET_CHALLENGE_PROBLEM_FAILURE: null,

    GET_DELETE_PROBLEM_NOTE_SUCCESS: null,
    GET_DELETE_PROBLEM_NOTE_FAILURE: null,

    GET_SCROLL_PICTURE_SUCCESS: null,
    GET_SCROLL_PICTURE_FAILURE: null,
    UPDATE_SCROLL_PICTURE_SUCCESS: null,
    UPDATE_SCROLL_PICTURE_FAILURE: null,
    ADD_SCROLL_PICTURE_SUCCESS: null,
    ADD_SCROLL_PICTURE_FAILURE: null,

    DELETE_TAG_SUCCESS: null,
    DELETE_TAG_FAILURE: null,

    GET_NEWESTNEWSROLL_SUCCESS:null,
    GET_NEWESTNEWSROLL_FAILURE:null,

    PROBLEM_TO_HEADER:null,

    UPDATE_PROBLEM_NOTE_SUCCESS:null,
    UPDATE_PROBLEM_NOTE_FAILURE:null,

    GET_ONLINENUM_SUCCESS:null,
    GET_ONLINENUM_FAILURE:null,

    GET_ALL_USERNUM_SUCCESS:null,
    GET_ALL_USERNUM_FAILURE:null,

    PWCHANGE_TO_HEADER:null,
    

    GET_CONTEST_NEWS_SUCCESS:null,
    GET_CONTEST_NEWS_FAILURE:null,

    GET_CONTEST_TEAM_SUCCESS:null,
    GET_CONTEST_TEAM_FAILURE:null,

    ADD_CONNTESTTEAM_SUCCESS:null,
    ADD_CONNTESTTEAM_FAILURE:null,

    GET_ONLINE_SUCCESS:null,
    GET_ONLINE_FAILURE:null,

    GET_ALL_CONTEST_SUCCESS:null,
    GET_ALL_CONTEST_FAILURE:null,
});